//! A5 — compliance report generator. Run with:
//!   cargo test --test manchester_conformance -- --ignored generate_compliance_report
use super::*;
use std::fmt::Write as _;

fn tick(b: bool) -> &'static str {
    if b { "PASS" } else { "FAIL" }
}

#[test]
#[ignore]
fn generate_compliance_report() {
    let mut md = String::new();
    writeln!(md, "# Manchester `io/omn` Compliance Report\n").unwrap();
    writeln!(
        md,
        "_Generated by `tests/manchester` (A1 construct matrix, A2 corpus, \
        A3 axiom-equality, A4 adversarial). Regenerate with \
        `cargo test --test manchester_conformance -- --ignored generate_compliance_report`._\n"
    )
    .unwrap();

    // -------------------------------------------------------------------------
    // A1 — §2.5 per-construct coverage matrix
    // -------------------------------------------------------------------------
    writeln!(md, "## A1 — §2.5 per-construct coverage matrix\n").unwrap();
    let (mut n_pass, mut n_resid) = (0usize, 0usize);
    let mut a1_rows = String::new();
    for c in constructs::CASES {
        let r = constructs::run_case(c);
        let is_resid = r.residual != constructs::Residual::None;
        if is_resid {
            n_resid += 1;
        } else if r.read_ok && r.note.is_empty() && r.roundtrip_ok {
            n_pass += 1;
        }
        writeln!(
            a1_rows,
            "| {} | {} | {} | {} | {:?} | {} |",
            r.id,
            tick(r.read_ok),
            tick(r.write_ok),
            tick(r.roundtrip_ok),
            r.residual,
            r.note.replace('|', "\\|")
        )
        .unwrap();
    }
    writeln!(
        md,
        "{} constructs pass read+write+round-trip; {} documented residuals.\n",
        n_pass, n_resid
    )
    .unwrap();
    writeln!(md, "| id | read | write | round-trip | residual | note |").unwrap();
    writeln!(md, "|----|------|-------|-----------|----------|------|").unwrap();
    md.push_str(&a1_rows);

    // -------------------------------------------------------------------------
    // A2 — corpus parse + structural round-trip
    // -------------------------------------------------------------------------
    writeln!(md, "\n## A2 — corpus parse + structural round-trip\n").unwrap();
    if corpus::docker_available() {
        writeln!(
            md,
            "| ontology | bytes | parse | components | round-trip | blocking |"
        )
        .unwrap();
        writeln!(
            md,
            "|----------|-------|-------|-----------|-----------|----------|"
        )
        .unwrap();
        for r in corpus::run_corpus() {
            writeln!(
                md,
                "| {} | {} | {} | {} | {} | {} |",
                r.name,
                r.bytes,
                tick(r.parse_ok),
                r.components,
                tick(r.roundtrip_ok),
                r.blocking.replace('|', "\\|")
            )
            .unwrap();
        }

        // ---------------------------------------------------------------------
        // A3 — semantic axiom-set equality vs OWL-API
        // ---------------------------------------------------------------------
        writeln!(md, "\n## A3 — semantic axiom-set equality vs OWL-API\n").unwrap();
        writeln!(
            md,
            "Source -> ROBOT(.ofn) -> ofn reader = truth; -> ROBOT(.omn) -> omn reader = candidate; \
            compared after canonicalization (declarations + non-logical meta dropped).\n"
        )
        .unwrap();
        writeln!(md, "| ontology | matched | missing | extra |").unwrap();
        writeln!(md, "|----------|---------|---------|-------|").unwrap();
        for r in canonical::run_axiom_equality() {
            writeln!(
                md,
                "| {} | {} | {} | {} |",
                r.name,
                r.matched,
                r.missing.len(),
                r.extra.len()
            )
            .unwrap();
        }
    } else {
        writeln!(md, "_SKIPPED — docker/ROBOT not available on this host._").unwrap();
    }

    // -------------------------------------------------------------------------
    // A4 — adversarial / fuzz
    // -------------------------------------------------------------------------
    writeln!(md, "\n## A4 — adversarial / fuzz\n").unwrap();
    writeln!(
        md,
        "Edge fixtures (unicode IRIs & literals, deep nesting, CRLF, dotted CURIEs) \
        read + round-trip; 4000 proptest cases (2000 arbitrary + 2000 Manchester-ish) with \
        zero reader panics. Run `cargo test --test manchester_conformance -- edge_cases reader_never_panics`."
    )
    .unwrap();

    let out = std::path::Path::new("docs/manchester/compliance-report.md");
    std::fs::create_dir_all(out.parent().unwrap()).unwrap();
    std::fs::write(out, md).unwrap();
    eprintln!("wrote {}", out.display());
}
