use criterion::{AxisScale, BenchmarkId, Criterion, PlotConfiguration, criterion_group};
use horned_bin::generate_big_owl;
use horned_owl::io::{ParserConfiguration, RDFParserConfiguration};
use horned_owl::model::RcStr;
use horned_owl::ontology::set::SetOntology;
use std::fs::{File, create_dir_all};
use std::io::BufReader;
use std::time::Duration;

fn bench_io_read(c: &mut Criterion) {
    let mut group = c.benchmark_group("io_read");
    group.plot_config(PlotConfiguration::default().summary_scale(AxisScale::Logarithmic));

    create_dir_all("target/bench-data").unwrap();
    // These files are generated by make bench-prepare from root directory of the project
    for n in [10, 100, 1_000, 2500, 5000, 10_000].iter() {
        let generate_if_needed = |filename, n: &isize, format| {
            let f = File::create_new(filename);
            // if the file is created, fill it, or do nothing
            if let Ok(mut f) = f {
                generate_big_owl(*n, format, &mut f).unwrap();
            }
        };

        let filename = format!("target/bench-data/o{}.owl", n);
        generate_if_needed(filename.clone(), n, "owl");

        group.bench_function(BenchmarkId::new("owl_io_read", n), |b| {
            b.iter(|| {
                let f = File::open(filename.clone()).ok().unwrap();
                let mut f = BufReader::new(f);
                let _ = horned_owl::io::rdf::reader::read(&mut f, Default::default()).ok();
            })
        });

        let filename = format!("target/bench-data/o{}.owx", n);
        generate_if_needed(filename.clone(), n, "owx");

        group.bench_function(BenchmarkId::new("owx_io_read", n), |b| {
            b.iter(|| {
                let f = File::open(filename.clone()).ok().unwrap();
                let mut f = BufReader::new(f);
                let _: (SetOntology<RcStr>, _) =
                    horned_owl::io::owx::reader::read(&mut f, Default::default())
                        .ok()
                        .unwrap();
            })
        });

        let filename = format!("target/bench-data/o{}.ttl", n);
        generate_if_needed(filename.clone(), n, "ttl");
        group.bench_function(BenchmarkId::new("ttl_io_read", n), |b| {
            b.iter(|| {
                let f = File::open(filename.clone()).ok().unwrap();
                let mut f = BufReader::new(f);
                let _ = horned_owl::io::rdf::reader::read(
                    &mut f,
                    ParserConfiguration {
                        rdf: RDFParserConfiguration {
                            format: Some(oxrdfio::RdfFormat::Turtle),
                        },
                        ..Default::default()
                    },
                )
                .ok();
            })
        });
    }
}

criterion_group! {
    name = io_read;
    config = Criterion::default()
    .sample_size(50)
    .measurement_time(Duration::from_secs(20));
    targets = bench_io_read
}
